### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by dmx1357** [CARNIVAL-IITP/Speech_source_separation#5]
In main.py line 50, a Solver module is called without a 'speaker_model' argument.
https://github.com/CARNIVAL-IITP/Speech_source_separation/blob/b99499f5599c6296ff02252fe88f5459ec569e47/main.py#L50

However, in src/solver.py, a 'speaker_model' argument is required.
https://github.com/CARNIVAL-IITP/Speech_source_separation/blob/b99499f5599c6296ff02252fe88f5459ec569e47/src/solver.py#L14

**Comment by BeomJunWoo** [comment]
Fixed the code of main.py and src/solver.py
